# Server
server.port=8443

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/innovativequotes
spring.datasource.username=postgres
spring.datasource.password=JaxxonKade12

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=Innovative2024!QuoteBuilder#SecureKey$Random123
jwt.expiration=86400000

# Logging
logging.level.org.innovative=DEBUG
logging.level.org.springframework.security=INFO

server.ssl.key-store=classpath:innovative.p12
server.ssl.key-store-password=innovative123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=innovative

# Gmail settings for mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=innovativequotesystem@gmail.com
spring.mail.password=gekp ugew ncqs anud
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Registration
app.company.code=InonovativeCode714!!
app.base.url=https://innovativeqb.ddns.net
